### ISSUE TITLE
Login not working in AntennaPod

### ISSUE THREAD

**Issue by seigakaku** [oxtyped/gpodder2go#1]
I run the server:

`./gpodder2go init`
`VERIFIER_SECRET_KEY="test" ./gpodder2go serve --addr 10.100.0.1:3005 --no-auth`

Create user:

`./gpodder2go accounts --api-addr='10.100.0.1:3005' create soz --name="soz" --email="test@gmail.com" --password="test"`

It reports 'User soz created!'

However, when trying to login from AntennaPod, this happens:

![photo_2022-11-26_18-44-29](https://user-images.githubusercontent.com/106838684/204110070-359a5243-7863-4de7-b56a-c7c05d4c575b.jpg)

On the terminal it shows:
`2022/11/26 18:43:19 [tamandua/dz6KGee0SZ-000001] "POST http://10.100.0.1:3005/api/2/auth/soz/login.json HTTP/1.1" from 10.100.0.7:49978 - 401 0B in 478.362µs`

However, it does work on the gPodder desktop client.

Am I doing something wrong in AntennaPod? Thanks in advance.

**Comment by davidchua** [comment]
Hi @seigakaku,

Thanks for bringing this up. I have managed to replicate the issue and will be releasing a fix shortly!

**Comment by oxtyped** [comment]
@seigakaku sorry that you're experiencing this error.

I've released https://github.com/oxtyped/gpodder2go/releases/tag/v0.1.1 which should fix this.

Do let me know if you're still having problems with this.

**Comment by seigakaku** [comment]
It worked, logged in and the sync was successful, thank you very much, this is a very useful app.

**Comment by oxtyped** [comment]
Glad that its resolved! Thank you for the kind comments! ❤️ 🙇 

Closing this issue. But do let me know if you run into any other issues!
