### ISSUE TITLE
Update libc and sqlite to compile on FreeBSD

### ISSUE THREAD

**Issue by dnebdal** [oxtyped/gpodder2go#15]
Hi. The version of modernc.org/libc and modernc.org/sqlite you currently use don't compile on FreeBSD, but just updating to
```
        modernc.org/libc v1.24.1 // indirect
        modernc.org/sqlite v1.26.0
```
was enough to make it compile and produce a running binary. With the caveat that I haven't actually tested it beyond seeing if it starts at all.

**Comment by davidchua** [comment]
Hi @dnebdal, thanks for sharing this issue.

I've tested a build for freebsd with your proposed changes. All looks good so far.

Let me do some further tests and release an update soon.

Thanks again! 🙇

**Comment by oxtyped** [comment]
Hi @dnebdal, thanks for sharing this issue.

I've tested a build for freebsd with your proposed changes. All looks good so far.

Let me do some further tests and release an update soon.

Thanks again! 🙇

**Comment by oxtyped** [comment]
b04261aea0b5839382d00fe6e037f082a7fae48d fixes this issue

**Comment by oxtyped** [comment]
Closing due to fixed
