### ISSUE TITLE
gPodder subscriptions not syncing

### ISSUE THREAD

**Issue by jpeeler** [oxtyped/gpodder2go#27]
When I click "restore subscriptions from gpodder.net", enter in my hosting URL, and then login I see this in the logs:

2024/04/23 22:44:54 [e0e267359302/8lsLJcgZ8n-000071] "GET http://localhost:3005/subscriptions/jpeeler.opml HTTP/1.1" from 10.0.2.100:51636 - 400 0B in 27.642µs
2024/04/23 22:44:54 http: named cookie not present

The subscriptions do not sync. Am I doing anything wrong?

Using https://github.com/oxtyped/gpodder2go/pkgs/container/gpodder2go/206777676?tag=main
 sha256:e91cce9f36a0ee32f89c0028d85bb37fcbb92b3e95b936013b34462b14f88189

Antennaepod seems to sync correctly, but hard to test without another working client.

**Comment by oxtyped** [comment]
@jpeeler thanks for the feedback!

Can I get more details on the client (and version number if its available) you're using and also on which OS?

**Comment by jpeeler** [comment]
For AntennaPod? It's version 3.3.2 on Android 14.

**Comment by oxtyped** [comment]
Thanks!

Could you share your steps to getting to "restore subscriptions from gpodder.net"?

I'm seeing some strange behavior on my antennapod too that seems to be making calls to an invalid device id during the sync flow (which may be unrelated).

Just wanted to make sure I got the right replication steps as I am unable to replicate when calling the api call of my user's `/subscriptions/user.opml` directly.

**Comment by jpeeler** [comment]
Sorry, I completely forgot what I was talking about... 
I'm using gPodder version 3.11.4 via a flatpak.

Click "check for new episodes", "restore my subscriptions from gpodder.net", and then login. I'm no longer seeing the same error message in the logs, so I don't know what's going on. However, the subscriptions aren't showing up in gPodder.

Also don't see an opml file anywhere if it's supposed to exist.

**Comment by oxtyped** [comment]
Thanks @jpeeler. I am unable to replicate this on my previous build (was able to get the opml when calling the endpoint directly).

On gpodder client itself (3.11.4), I can't find the "restore my subscriptions from gpodder.net" (although I believe I've seen this button before). If you can, could you share with me which window you opened to get to this?

Thanks and really appreciate your patience on this!

**Comment by jpeeler** [comment]
I should have clarified that the "check for new episodes" button is in the bottom left.

https://dl.flathub.org/repo/screenshots/org.gpodder.gpodder-stable/1504x846/org.gpodder.gpodder-53b9ef56cb2ecfc2016aae2d8cf456d6.png

(copied from https://flathub.org/apps/org.gpodder.gpodder)

Maybe it requires a fresh state and doesn't behave the same way if you have any subscriptions already setup. This screen is shown after clicking "check for new episodes":

![image](https://github.com/oxtyped/gpodder2go/assets/834161/8c7bc5ad-7e00-4d5c-84d8-fbda50a2bf79)

**Comment by jpeeler** [comment]
I'm closing this as I was setting NO_AUTH=false and completely forgot about [the limitations](https://github.com/oxtyped/gpodder2go/blob/25adb9ce7d1b100745b04885a6a35e186ed731c2/README.md#limitations) that was outlined for gpodder.
