### ISSUE TITLE
Cannot build for armv7

### ISSUE THREAD

**Issue by gpasqualetti** [oxtyped/gpodder2go#3]
When I try to build for armv7 in a Docker container, I receive the following error:

> [7/8] RUN cd gpodder2go && ./gpodder2go init:
#10 0.770 panic: suint(-301924841) expects input >= 0
#10 0.771 
#10 0.771 goroutine 24 [running]:
#10 0.772 github.com/golang-migrate/migrate/v4.suint(...)
#10 0.773 	/go/pkg/mod/github.com/golang-migrate/migrate/v4@v4.15.2/util.go:46
#10 0.774 github.com/golang-migrate/migrate/v4.(*Migrate).readUp(0x25426c0, 0xffffffff, 0xffffffff, 0x2542880)
#10 0.776 	/go/pkg/mod/github.com/golang-migrate/migrate/v4@v4.15.2/migrate.go:582 +0x7b8
#10 0.779 created by github.com/golang-migrate/migrate/v4.(*Migrate).Up
#10 0.779 	/go/pkg/mod/github.com/golang-migrate/migrate/v4@v4.15.2/migrate.go:283 +0x10c

The problem seems to be some option of migrate already reported here, together with a possible solution: https://github.com/golang-migrate/migrate/issues/213

**Comment by oxtyped** [comment]
Thanks for reporting this and linking the upstream issue too.

Seems like changing the migration format with `migrate create -format` or `migrate create -seq` would be a quick workaround to this issue on armv7.

**Comment by oxtyped** [comment]
Any reviews will be appreciated!

**Comment by gpasqualetti** [comment]
Thank you for the patch! I tested it and the problem seems to be solved.
