### ISSUE TITLE
using modernc.org/sqlite instead of cgo-based SQLite client ?

### ISSUE THREAD

**Issue by sbinet** [oxtyped/gpodder2go#5]
hi there,

would it be ok to use `modernc.org/sqlite` ?
it would allow easy cross-compilation (from, say, anything to a RPi)

**Comment by oxtyped** [comment]
Hello 👋 

Yes! This actually has been one of the things I have been thinking of doing for a while now.

I will look into it, but if you want to open up a PR for this in the meantime, please don't let me stop you!

**Comment by oxtyped** [comment]
@sbinet how can I replicate the cross-compilation failure from go-sqlite3 and the lack of cgo?

**Comment by sbinet** [comment]
a simple way to test it is like:

```
$> GOARCH=arm64 CGO_ENABLED=0 go build
```

**Comment by oxtyped** [comment]
Thanks!

Oddly, I can't replicate this now (on mattn) while trying to cross compile across various arch. 

I know this shouldn't be the case because I have exactly got stuck on this before.
